# GitHub Pages Configuration for MCP-GIS Research Hub
title: "AI-Driven Spatial Distribution Research Hub"
description: "Interactive dashboards and comprehensive analysis of AI implementation effects on spatial economic patterns in Japan's aging society"
url: "https://tatsuru-kikuchi.github.io"
baseurl: "/MCP-gis"

# Build settings
markdown: kramdown
highlighter: rouge

# Exclude files from processing
exclude:
  - README.md
  - Gemfile
  - Gemfile.lock
  - node_modules
  - vendor
  - .sass-cache
  - .jekyll-cache
  - "*.py"
  - "*.txt"
  - "*.yml"
  - data/
  - logs/
  - results/
  - script/
  - web_dashboard/
  - dynamic_analysis/
  - manuscript_optimized/
  - notebooks/
  - visualization/
  - visualizations/
  - config/

# Include only docs content
include:
  - docs/

# SEO settings
author: "Tatsuru Kikuchi"
social:
  - https://github.com/Tatsuru-Kikuchi

# Custom variables
research:
  title: "AI-Driven Spatial Distribution Analysis"
  subtitle: "Tokyo Metropolitan Area Study"
  keywords: "AI, spatial economics, aging society, causal inference"
