# Simple GitHub Pages Configuration
title: "AI-Driven Spatial Distribution Research"
description: "Research presentation and key findings overview"
url: "https://tatsuru-kikuchi.github.io"
baseurl: "/MCP-gis"

# Keep it simple for static HTML
markdown: kramdown
highlighter: rouge

# Exclude everything except docs content
exclude:
  - README.md
  - "*.py"
  - "*.txt"
  - "*.yml"
  - "*.json"
  - data/
  - logs/
  - results/
  - script/
  - web_dashboard/
  - dynamic_analysis/
  - manuscript_optimized/
  - notebooks/
  - visualization/
  - visualizations/
  - config/
  - .cache/

# Basic SEO
author: "Tatsuru Kikuchi"
